
opening.bnr: opening.ppm
	../ppm2bnr/ppm2bnr -n "iso9660 bootable disc" -c "www.gc-linux.org" -N "GNU/Linux on the Nintendo GameCube" -C "www.gc-linux.org" $< -o $@


clean:
	rm -f \
		*~

dist-clean: clean
	rm -f \
		opening.bnr

dummy:

